GET HTTP://localhost:3000/blocks

###
POST HTTP://localhost:3000/blocks
content-type: application/json

{
    "data" : "second blocks"
}

###
POST HTTP://localhost:3000/peers
content-type: application/json

{
    "peer" : "ws://localhost:4000"
}

###
get HTTP://localhost:3000/me/balance